name: deentok
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.8.0
  video_player: ^2.5.1
  visibility_detector: ^0.4.0+2
  google_fonts: ^4.0.4

  go_router: ^14.6.3
  camera: ^0.11.0+2

  permission_handler: ^11.3.1

  # gallery_saver: 

  image_picker: ^1.1.2

  provider: ^6.1.2
  shared_preferences: ^2.1.1

  flutter_riverpod: ^2.1.3
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  cloud_functions: ^5.2.0
  firebase_messaging: ^15.1.6
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/videos/sample.mp4
    - assets/images/placeholder.jpg
flutter_intl:
  enabled: true
